const state={config:{apiBaseUrl:"",wsBaseUrl:""},token:"",username:"",tagCatalog:{mainCategories:[{categoryCode:"MAIN_GRADE",categoryName:"年级",options:[{tagCode:"UNCATEGORIZED",tagName:"未分类"}]},{categoryCode:"MAIN_KNOWLEDGE",categoryName:"知识点",options:[{tagCode:"UNCATEGORIZED",tagName:"未分类"}]}],secondaryCategoryCode:"SECONDARY_CUSTOM",secondaryCategoryName:"副标签"},ws:null,wsConnected:false,selectedQuestionUuid:"",stageFilter:"PENDING_STEM",entries:new Map(),ocrTasks:new Map(),contextMenuQuestionUuid:""};
const KATEX_DELIMITERS=[{left:"$$",right:"$$",display:true},{left:"$",right:"$",display:false},{left:"\\(",right:"\\)",display:false},{left:"\\[",right:"\\]",display:true}];
const $=id=>document.getElementById(id);
const stageOf=e=>!e?"PENDING_STEM":e.status==="READY"?"COMPLETED":e.stemConfirmed?"PENDING_ANSWER":"PENDING_STEM";
const stageText=s=>s==="PENDING_STEM"?"待题干确认":s==="PENDING_ANSWER"?"待录答案":s==="COMPLETED"?"已完成":s;
const stageCls=s=>s==="COMPLETED"?"success":s==="PENDING_ANSWER"?"warn":"neutral";
const errMsg=e=>(e&&e.data&&e.data.message)||(e&&e.message)||"Unknown error";
const now=()=>new Date().toLocaleTimeString();
function log(m){const box=$("event-log");if(!box)return;const li=document.createElement("li");li.textContent=`${now()}  ${m}`;box.prepend(li)}
function storageKey(){return `qforge.demo.workspace.${state.username}`}
function normalizeCatalog(raw){const main=(Array.isArray(raw&&raw.mainCategories)?raw.mainCategories:[]).map(c=>({categoryCode:String(c?.categoryCode||"").trim(),categoryName:String(c?.categoryName||"").trim(),options:(Array.isArray(c?.options)?c.options:[]).map(o=>({tagCode:String(o?.tagCode||"").trim(),tagName:String(o?.tagName||"").trim()})).filter(o=>o.tagCode)})).filter(c=>c.categoryCode);for(const c of main){if(!c.options.length)c.options=[{tagCode:"UNCATEGORIZED",tagName:"未分类"}]};return{mainCategories:main.length?main:state.tagCatalog.mainCategories,secondaryCategoryCode:String(raw?.secondaryCategoryCode||"SECONDARY_CUSTOM").trim()||"SECONDARY_CUSTOM",secondaryCategoryName:String(raw?.secondaryCategoryName||"副标签").trim()||"副标签"}}
function parseSecondaryTags(t){const x=String(t||"").trim();return x?[...new Set(x.split(/\s+/g).map(s=>s.trim()).filter(Boolean))]:[]}
function ensureMainTags(entry){const cur=new Map((entry.mainTags||[]).map(t=>[t.categoryCode,t]));entry.mainTags=state.tagCatalog.mainCategories.map(c=>{const old=cur.get(c.categoryCode);if(old)return{categoryCode:c.categoryCode,categoryName:c.categoryName||old.categoryName,tagCode:old.tagCode,tagName:old.tagName||old.tagCode};const d=c.options[0]||{tagCode:"UNCATEGORIZED",tagName:"未分类"};return{categoryCode:c.categoryCode,categoryName:c.categoryName||c.categoryCode,tagCode:d.tagCode,tagName:d.tagName||d.tagCode}});if(!entry.secondaryTagsDraft)entry.secondaryTagsDraft=(entry.secondaryTags||[]).join(" ")}
function ensureAnswerViewIndex(entry){const total=Array.isArray(entry.answersLocal)?entry.answersLocal.length:0;const idx=Number.isInteger(entry.answerViewIndex)?entry.answerViewIndex:0;if(total<=0){entry.answerViewIndex=0;return}entry.answerViewIndex=Math.max(0,Math.min(idx,total-1))}
function normalizeEntry(raw){const e={questionUuid:raw.questionUuid,status:raw.status||"DRAFT",stemText:raw.stemText||"",stemDraft:raw.stemDraft||raw.stemText||"",stemConfirmed:Boolean(raw.stemConfirmed),mainTags:Array.isArray(raw.mainTags)?raw.mainTags:[],secondaryTags:Array.isArray(raw.secondaryTags)?raw.secondaryTags:[],secondaryTagsDraft:raw.secondaryTagsDraft||"",answerCount:Number(raw.answerCount||0),answerDraft:raw.answerDraft||"",answersLocal:Array.isArray(raw.answersLocal)?raw.answersLocal:[],answerViewIndex:Number.isInteger(raw.answerViewIndex)?raw.answerViewIndex:0,lastOcrTaskUuid:raw.lastOcrTaskUuid||"",lastOcrStatus:raw.lastOcrStatus||"",updatedAt:Number(raw.updatedAt||Date.now())};ensureMainTags(e);ensureAnswerViewIndex(e);if(!e.secondaryTagsDraft)e.secondaryTagsDraft=(e.secondaryTags||[]).join(" ");return e}
function saveWorkspace(){if(!state.username)return;localStorage.setItem(storageKey(),JSON.stringify({entries:[...state.entries.values()],ocrTasks:[...state.ocrTasks.values()],selectedQuestionUuid:state.selectedQuestionUuid||""}))}
function loadWorkspace(){if(!state.username)return;state.entries.clear();state.ocrTasks.clear();state.selectedQuestionUuid="";const raw=localStorage.getItem(storageKey());if(!raw)return;try{const o=JSON.parse(raw);for(const it of o.entries||[]){const e=normalizeEntry(it);state.entries.set(e.questionUuid,e)}for(const t of o.ocrTasks||[])state.ocrTasks.set(t.taskUuid,t);if(o.selectedQuestionUuid&&state.entries.has(o.selectedQuestionUuid))state.selectedQuestionUuid=o.selectedQuestionUuid}catch{}}
function selectedEntry(){return state.entries.get(state.selectedQuestionUuid)||null}
function selectedTask(){const e=selectedEntry();return!e||!e.lastOcrTaskUuid?null:state.ocrTasks.get(e.lastOcrTaskUuid)||null}
function setLoggedIn(v){$("login-screen").classList.toggle("hidden",v);$("app-shell").classList.toggle("hidden",!v);$("current-user").textContent=v?state.username:"";const s=$("status-user");if(s)s.textContent=v?`用户: ${state.username}`:"访客"}
function updateWs(){const n=$("ws-indicator");n.classList.toggle("connected",state.wsConnected);n.classList.toggle("disconnected",!state.wsConnected);n.textContent=state.wsConnected?"已连接":"未连接";const c=$("status-connection");if(c){c.classList.toggle("connected",state.wsConnected);c.classList.toggle("disconnected",!state.wsConnected);c.textContent=state.wsConnected?"连接: 已连接":"连接: 未连接"}}
function updateStatusBar(){const node=$("status-stage-summary");if(!node)return;const e=selectedEntry();if(!e){node.textContent="未选择任务";return}node.textContent=`${stageText(stageOf(e))} · 答案 ${Number(e.answerCount||0)} · ${e.questionUuid.slice(0,8)}...`}
function hideMenu(){const m=$("entry-context-menu");m.classList.add("hidden");m.style.left="-9999px";m.style.top="-9999px"}
function showMenu(x,y,qid){const m=$("entry-context-menu");$("entry-delete-action").dataset.questionUuid=qid;m.classList.remove("hidden");const r=m.getBoundingClientRect();m.style.left=`${Math.min(x,Math.max(8,window.innerWidth-r.width-8))}px`;m.style.top=`${Math.min(y,Math.max(8,window.innerHeight-r.height-8))}px`}
function canDelete(e){const s=stageOf(e);return(s==="PENDING_STEM"||s==="PENDING_ANSWER")&&e.status==="DRAFT"&&Number(e.answerCount||0)===0}
function setTag(node,text,css){node.textContent=text;node.className=`tag ${css}`}
function renderLatexNode(node,text,placeholder){const c=(text||"").trim();if(!c){node.textContent=placeholder;return}node.textContent=c;if(typeof window.renderMathInElement==="function")try{window.renderMathInElement(node,{delimiters:KATEX_DELIMITERS,throwOnError:false,strict:"ignore"})}catch{}}
const renderLatex=(id,text,ph)=>renderLatexNode($(id),text,ph);
function renderMainSelectors(entry,editable){const box=$("stem-main-tag-container");box.innerHTML="";if(!state.tagCatalog.mainCategories.length){box.innerHTML='<div class="empty-note">暂无主标签字典</div>';return}const map=new Map((entry.mainTags||[]).map(t=>[t.categoryCode,t]));for(const c of state.tagCatalog.mainCategories){const row=document.createElement("div");row.className="row";const lab=document.createElement("label");lab.className="tag-edit-label";lab.textContent=`${c.categoryName}主标签`;const sel=document.createElement("select");for(const o of c.options){const op=document.createElement("option");op.value=o.tagCode;op.textContent=o.tagName||o.tagCode;sel.appendChild(op)}const cur=map.get(c.categoryCode);sel.value=cur?.tagCode||c.options[0]?.tagCode||"UNCATEGORIZED";sel.disabled=!editable;sel.addEventListener("change",()=>{const opt=c.options.find(x=>x.tagCode===sel.value);const tags=[...(entry.mainTags||[])];const i=tags.findIndex(t=>t.categoryCode===c.categoryCode);const next={categoryCode:c.categoryCode,categoryName:c.categoryName,tagCode:sel.value,tagName:opt?.tagName||sel.value};if(i>=0)tags[i]=next;else tags.push(next);entry.mainTags=tags;entry.updatedAt=Date.now();state.entries.set(entry.questionUuid,entry);saveWorkspace();$("detail-main-tags").textContent=entry.mainTags.map(t=>`${t.categoryName}:${t.tagName}`).join(" / ")});row.appendChild(lab);row.appendChild(sel);box.appendChild(row)}}
function renderHistory(entry){const b=$("answer-history");b.innerHTML="";if(!entry||!entry.answersLocal||!entry.answersLocal.length){b.innerHTML='<div class="empty-note">暂无已录入答案</div>';return}entry.answersLocal.forEach((ans,i)=>{const it=document.createElement("div");it.className="answer-history-item";const t=document.createElement("div");t.className="answer-history-index";t.textContent=`解法 #${i+1}`;const n=document.createElement("div");n.className="answer-history-latex";renderLatexNode(n,ans,"空答案");it.appendChild(t);it.appendChild(n);b.appendChild(it)})}
function renderCompletedView(entry){ensureAnswerViewIndex(entry);const answers=entry.answersLocal||[];const idx=entry.answerViewIndex;renderLatex("completed-stem-preview",entry.stemText||entry.stemDraft||"","题干渲染区");const tabs=$("completed-answer-tabs");tabs.innerHTML="";const page=$("completed-answer-page");const prev=$("completed-prev-answer");const next=$("completed-next-answer");if(!answers.length){page.textContent="0 / 0";prev.disabled=true;next.disabled=true;renderLatex("completed-answer-preview","","暂无答案");return}answers.forEach((_,i)=>{const btn=document.createElement("button");btn.className=`answer-tab ${i===idx?"active":""}`;btn.dataset.index=String(i);btn.textContent=`解法${i+1}`;tabs.appendChild(btn)});page.textContent=`${idx+1} / ${answers.length}`;prev.disabled=idx<=0;next.disabled=idx>=answers.length-1;renderLatex("completed-answer-preview",answers[idx]||"","暂无答案")}
function setCompletedAnswerIndex(index){const e=selectedEntry();if(!e)return;const total=Array.isArray(e.answersLocal)?e.answersLocal.length:0;if(total<=0)return;e.answerViewIndex=Math.max(0,Math.min(index,total-1));e.updatedAt=Date.now();state.entries.set(e.questionUuid,e);saveWorkspace();renderAll()}
function shiftCompletedAnswer(delta){const e=selectedEntry();if(!e)return;const start=Number.isInteger(e.answerViewIndex)?e.answerViewIndex:0;setCompletedAnswerIndex(start+delta)}
function renderList(){const list=$("entry-list");list.innerHTML="";const rows=[...state.entries.values()].filter(e=>stageOf(e)===state.stageFilter).sort((a,b)=>(b.updatedAt||0)-(a.updatedAt||0));if(!rows.length){list.innerHTML='<div class="empty-note">当前分类暂无任务</div>';return}for(const e of rows){const s=stageOf(e);const item=document.createElement("div");item.className=`entry-item ${e.questionUuid===state.selectedQuestionUuid?"active":""}`;item.innerHTML=`<div class="entry-title">${e.questionUuid}</div><div class="entry-sub"><span>答案 ${e.answerCount||0}</span><span class="tag ${stageCls(s)}">${stageText(s)}</span></div>`;item.addEventListener("click",()=>{state.selectedQuestionUuid=e.questionUuid;saveWorkspace();renderAll()});item.addEventListener("contextmenu",ev=>{ev.preventDefault();if(!canDelete(e)){hideMenu();return}state.selectedQuestionUuid=e.questionUuid;state.contextMenuQuestionUuid=e.questionUuid;saveWorkspace();renderAll();showMenu(ev.clientX,ev.clientY,e.questionUuid)});list.appendChild(item)}}
function renderDetail(){const e=selectedEntry();const t=selectedTask();const split=$("split-workspace");const stem=$("stem-work-card");const ans=$("answer-work-card");const done=$("completed-work-card");const ansLayout=$("answer-edit-layout");const ansOcr=$("answer-ocr-btn");const ansRender=$("render-answer-btn");const secIn=$("stem-secondary-tags-input");$("detail-question-uuid").textContent=e?e.questionUuid:"-";$("detail-question-status").textContent=e?e.status:"-";$("detail-answer-count").textContent=e?String(e.answerCount||0):"0";$("detail-main-tags").textContent=e&&e.mainTags?.length?e.mainTags.map(x=>`${x.categoryName}:${x.tagName}`).join(" / "):"未分类";$("detail-secondary-tags").textContent=e&&e.secondaryTags?.length?e.secondaryTags.join(" "):"-";const stageTag=$("detail-stage-tag");const stemHint=$("stem-stage-hint");const ansHint=$("answer-stage-hint");const lock=$("answer-lock-tip");if(!e){split.classList.add("single-pane");stem.classList.remove("hidden");ans.classList.add("hidden");done.classList.add("hidden");setTag(stageTag,"-","neutral");setTag(stemHint,"-","neutral");setTag(ansHint,"-","neutral");$("detail-ocr-task").textContent="-";setTag($("detail-ocr-status"),"-","neutral");$("stem-textarea").value="";$("answer-textarea").value="";secIn.value="";renderMainSelectors({mainTags:[]},false);renderLatex("stem-preview","","题干 LaTeX 预览区域");renderLatex("answer-stem-preview","","题干 LaTeX 只读预览区域");renderLatex("answer-preview","","答案 LaTeX 预览区域");renderLatex("completed-stem-preview","","题干渲染区");renderLatex("completed-answer-preview","","答案渲染区");$("completed-answer-tabs").innerHTML="";$("completed-answer-page").textContent="1 / 1";$("completed-prev-answer").disabled=true;$("completed-next-answer").disabled=true;renderHistory(null);ansLayout.classList.remove("hidden");ansOcr.classList.remove("hidden");ansRender.classList.remove("hidden");lock.classList.add("hidden");$("start-ocr-btn").disabled=true;$("confirm-stem-btn").disabled=true;$("use-ocr-result-btn").disabled=true;$("answer-textarea").disabled=true;$("add-answer-btn").disabled=true;$("complete-btn").disabled=true;return}
ensureMainTags(e);ensureAnswerViewIndex(e);const stage=stageOf(e);const onlyStem=stage==="PENDING_STEM";const pendingAnswer=stage==="PENDING_ANSWER";const completed=stage==="COMPLETED";split.classList.add("single-pane");stem.classList.toggle("hidden",!onlyStem);ans.classList.toggle("hidden",onlyStem||completed);done.classList.toggle("hidden",!completed);renderMainSelectors(e,onlyStem);setTag(stageTag,stageText(stage),stageCls(stage));if(stage==="PENDING_STEM"){setTag(stemHint,"待题干确认","warn");setTag(ansHint,"等待题干确认","warn")}else if(stage==="PENDING_ANSWER"){setTag(stemHint,"题干已确认","success");setTag(ansHint,"待录答案","warn")}else{setTag(stemHint,"题干已完成","success");setTag(ansHint,"答案流程完成","success")}
$("detail-ocr-task").textContent=e.lastOcrTaskUuid||"-";const os=t?t.status:"-";if(os==="SUCCESS")setTag($("detail-ocr-status"),"SUCCESS","success");else if(os==="FAILED")setTag($("detail-ocr-status"),"FAILED","fail");else if(os==="PENDING"||os==="PROCESSING")setTag($("detail-ocr-status"),os,"warn");else setTag($("detail-ocr-status"),os,"neutral");if(document.activeElement!==$("stem-textarea"))$("stem-textarea").value=e.stemDraft||e.stemText||"";if(document.activeElement!==$("answer-textarea"))$("answer-textarea").value=e.answerDraft||"";if(document.activeElement!==secIn)secIn.value=e.secondaryTagsDraft||e.secondaryTags.join(" ");renderLatex("stem-preview",$("stem-textarea").value,"题干 LaTeX 预览区域");renderLatex("answer-stem-preview",e.stemText||e.stemDraft||"","题干 LaTeX 只读预览区域");renderLatex("answer-preview",$("answer-textarea").value,"答案 LaTeX 预览区域");renderHistory(e);renderCompletedView(e);ansLayout.classList.toggle("hidden",!pendingAnswer);ansOcr.classList.toggle("hidden",!pendingAnswer);ansRender.classList.toggle("hidden",!pendingAnswer);$("start-ocr-btn").disabled=!onlyStem;$("confirm-stem-btn").disabled=!onlyStem;$("use-ocr-result-btn").disabled=!(t&&t.recognizedText);secIn.disabled=!onlyStem;$("answer-textarea").disabled=!pendingAnswer;$("add-answer-btn").disabled=!pendingAnswer;$("complete-btn").disabled=!pendingAnswer;lock.classList.toggle("hidden",pendingAnswer||completed)}
function renderFilters(){document.querySelectorAll(".filter-btn").forEach(b=>b.classList.toggle("active",b.dataset.stage===state.stageFilter))}
function renderAll(){renderFilters();renderList();renderDetail();updateWs();updateStatusBar()}
async function api(path,method,body){return window.qforge.api.request(path,method,state.token,body)}
async function loadTags(){try{const r=await api("/api/tags","GET");state.tagCatalog=normalizeCatalog(r.data||{});for(const e of state.entries.values())ensureMainTags(e)}catch(e){log(`标签字典加载失败: ${errMsg(e)}`)}}
function wsUrl(){const root=state.config.wsBaseUrl.endsWith("/")?state.config.wsBaseUrl.slice(0,-1):state.config.wsBaseUrl;return `${root}/ws/questions?user=${encodeURIComponent(state.username)}`}
function upsertWs(msg){const p=msg.payload||{};if(!p.taskUuid)return;const old=state.ocrTasks.get(p.taskUuid)||{taskUuid:p.taskUuid,questionUuid:p.bizId||"",status:"PENDING",recognizedText:"",errorMessage:"",updatedAt:Date.now()};if(msg.event==="ocr.task.succeeded"){old.status="SUCCESS";old.recognizedText=p.recognizedText||"";old.errorMessage="";log(`OCR成功: ${p.taskUuid}`)}else if(msg.event==="ocr.task.failed"){old.status="FAILED";old.errorMessage=p.errorMessage||"Unknown error";log(`OCR失败: ${p.taskUuid}`)}old.updatedAt=Date.now();state.ocrTasks.set(p.taskUuid,old);const e=state.entries.get(p.bizId);if(e){e.lastOcrTaskUuid=p.taskUuid;e.lastOcrStatus=old.status;if(!e.stemDraft&&old.recognizedText)e.stemDraft=old.recognizedText;e.updatedAt=Date.now();state.entries.set(e.questionUuid,e)}}
function connectWs(){if(!state.username)return;if(state.ws){state.ws.close();state.ws=null}const ws=new WebSocket(wsUrl());state.ws=ws;ws.onopen=()=>{state.wsConnected=true;renderAll();log("WS已连接")};ws.onclose=()=>{state.wsConnected=false;renderAll();log("WS已断开")};ws.onerror=()=>{state.wsConnected=false;renderAll()};ws.onmessage=e=>{try{upsertWs(JSON.parse(e.data));saveWorkspace();renderAll()}catch{log("收到无法解析的WS消息")}}}
async function toBase64(file){return await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>{const raw=String(r.result||"");const idx=raw.indexOf(",");res(idx>=0?raw.slice(idx+1):raw)};r.onerror=()=>rej(new Error("读取图片失败"));r.readAsDataURL(file)})}
function createEntry(q){const stem=q.stemText||"";const ans=Array.isArray(q.answers)?q.answers:[];return normalizeEntry({questionUuid:q.questionUuid,status:q.status,stemText:stem,stemDraft:stem,stemConfirmed:Boolean(stem&&stem.trim()),mainTags:q.mainTags,secondaryTags:q.secondaryTags,answerCount:Number(q.answerCount||ans.length||0),answerDraft:"",answersLocal:ans.map(a=>a.latexText).filter(Boolean),answerViewIndex:0,lastOcrTaskUuid:"",lastOcrStatus:"",updatedAt:Number(q.updatedAt?new Date(q.updatedAt).getTime():Date.now())})}
async function createTask(){const r=await api("/api/questions","POST",{});const e=createEntry(r.data);state.entries.set(e.questionUuid,e);state.selectedQuestionUuid=e.questionUuid;saveWorkspace();renderAll();log(`新建任务: ${e.questionUuid}`)}
async function createBatch(){const n=Number($("batch-count").value||0);if(!Number.isFinite(n)||n<2||n>20)throw new Error("批量数量范围: 2-20");for(let i=0;i<n;i+=1)await createTask();log(`批量创建完成: ${n} 个任务`)}
async function submitStemOcrForEntry(e,imageBase64){const r=await api(`/api/questions/${e.questionUuid}/ocr-tasks`,`POST`,{imageBase64});const t={taskUuid:r.data.taskUuid,questionUuid:e.questionUuid,status:r.data.status||"PENDING",recognizedText:"",errorMessage:"",updatedAt:Date.now()};state.ocrTasks.set(t.taskUuid,t);e.lastOcrTaskUuid=t.taskUuid;e.lastOcrStatus=t.status;e.updatedAt=Date.now();state.entries.set(e.questionUuid,e);saveWorkspace();renderAll();return t.taskUuid}
async function submitStemOcr(){const e=selectedEntry();if(!e)throw new Error("请先选择任务");const f=$("ocr-image-input").files?.[0];if(!f)throw new Error("请先选择图片");const id=await submitStemOcrForEntry(e,await toBase64(f));log(`OCR任务已提交: ${id}`)}
function fillLatest(){const e=selectedEntry();const t=selectedTask();if(!e||!t||!t.recognizedText)throw new Error("当前任务没有可用识别结果");e.stemDraft=t.recognizedText;e.updatedAt=Date.now();state.entries.set(e.questionUuid,e);saveWorkspace();renderAll();log("已填充OCR结果到题干编辑区")}
async function confirmStem(){const e=selectedEntry();if(!e)throw new Error("请先选择任务");if(!e.lastOcrTaskUuid)throw new Error("请先发起并完成OCR任务");const confirmedText=$("stem-textarea").value.trim();if(!confirmedText)throw new Error("题干不能为空");ensureMainTags(e);const secondaryTagsText=(e.secondaryTagsDraft||"").trim();const mainTags=(e.mainTags||[]).map(t=>({categoryCode:t.categoryCode,tagCode:t.tagCode}));const r=await api(`/api/ocr-tasks/${e.lastOcrTaskUuid}/confirmations`,`POST`,{confirmedText,mainTags,secondaryTagsText});e.status=r.data.status;e.stemText=confirmedText;e.stemDraft=confirmedText;e.stemConfirmed=true;e.secondaryTags=parseSecondaryTags(secondaryTagsText);e.updatedAt=Date.now();state.entries.set(e.questionUuid,e);saveWorkspace();renderAll();log(`题干已确认: ${e.questionUuid}`)}
async function addAnswer(){const e=selectedEntry();if(!e)throw new Error("请先选择任务");if(!e.stemConfirmed)throw new Error("请先确认题干");const latexText=$("answer-textarea").value.trim();if(!latexText)throw new Error("答案不能为空");const r=await api(`/api/questions/${e.questionUuid}/answers`,`POST`,{latexText});e.status=r.data.status;e.answerCount=(e.answerCount||0)+1;e.answersLocal=[...(e.answersLocal||[]),latexText];e.answerViewIndex=Math.max(0,e.answersLocal.length-1);e.answerDraft="";e.updatedAt=Date.now();state.entries.set(e.questionUuid,e);saveWorkspace();renderAll();log(`答案已添加: ${e.questionUuid}`)}
async function completeQ(){const e=selectedEntry();if(!e)throw new Error("请先选择任务");const r=await api(`/api/questions/${e.questionUuid}/complete`,`POST`);e.status=r.data.status;ensureAnswerViewIndex(e);e.updatedAt=Date.now();state.entries.set(e.questionUuid,e);saveWorkspace();renderAll();log(`任务已完成(READY): ${e.questionUuid}`)}
async function delQ(qid){if(!qid)throw new Error("questionUuid is required");await api(`/api/questions/${qid}`,"DELETE");state.entries.delete(qid);state.contextMenuQuestionUuid="";for(const [id,t] of state.ocrTasks.entries())if(t.questionUuid===qid)state.ocrTasks.delete(id);if(state.selectedQuestionUuid===qid){const n=[...state.entries.values()].sort((a,b)=>(b.updatedAt||0)-(a.updatedAt||0))[0];state.selectedQuestionUuid=n?n.questionUuid:""}hideMenu();saveWorkspace();renderAll();log(`已删除未完成题目: ${qid}`)}
async function syncQuestions(){const r=await api("/api/questions","GET");const rows=Array.isArray(r.data)?r.data:[];const old=new Map(state.entries);const merged=new Map();for(const row of rows){const p=old.get(row.questionUuid);const stem=row.stemText||"";const ans=Array.isArray(row.answers)?row.answers:[];const ansText=ans.map(a=>a.latexText).filter(Boolean);const e=normalizeEntry({questionUuid:row.questionUuid,status:row.status||"DRAFT",stemText:stem,stemDraft:p?p.stemDraft||stem:stem,stemConfirmed:stem.trim().length>0||row.status==="READY",mainTags:row.mainTags,secondaryTags:row.secondaryTags,secondaryTagsDraft:p?p.secondaryTagsDraft:(Array.isArray(row.secondaryTags)?row.secondaryTags.join(" "):""),answerCount:Number(row.answerCount||ansText.length||0),answerDraft:p?p.answerDraft:"",answersLocal:ansText.length?ansText:(p?p.answersLocal:[]),answerViewIndex:p?p.answerViewIndex:0,lastOcrTaskUuid:p?p.lastOcrTaskUuid:"",lastOcrStatus:p?p.lastOcrStatus:"",updatedAt:Number.isFinite(new Date(row.updatedAt).getTime())?new Date(row.updatedAt).getTime():Date.now()});merged.set(row.questionUuid,e)}state.entries=merged;for(const [id,t] of state.ocrTasks.entries())if(!merged.has(t.questionUuid))state.ocrTasks.delete(id);if(!state.selectedQuestionUuid||!merged.has(state.selectedQuestionUuid)){const f=[...merged.values()].sort((a,b)=>(b.updatedAt||0)-(a.updatedAt||0))[0];state.selectedQuestionUuid=f?f.questionUuid:""}saveWorkspace();renderAll();log(`已同步题目: ${rows.length} 条`)}
async function createByShot(imageBase64){if(!state.token||!state.username)throw new Error("请先登录后再使用截图录题");if(!imageBase64)throw new Error("截图数据为空");const c=await api("/api/questions","POST",{});const e=createEntry(c.data);state.entries.set(e.questionUuid,e);state.selectedQuestionUuid=e.questionUuid;state.stageFilter="PENDING_STEM";const id=await submitStemOcrForEntry(e,imageBase64);log(`截图录题已创建任务并提交OCR: ${e.questionUuid} / ${id}`)}
function bind(){hideMenu();document.querySelectorAll(".filter-btn").forEach(b=>b.addEventListener("click",()=>{state.stageFilter=b.dataset.stage;hideMenu();renderAll()}));$("login-form").addEventListener("submit",async ev=>{ev.preventDefault();$("login-error").textContent="";const username=$("login-username").value.trim();const password=$("login-password").value;const remember=$("remember-password").checked;try{const login=await window.qforge.auth.login(username,password);state.token=login.accessToken;state.username=username;if(remember)await window.qforge.credentials.save({remember:true,username,password});else await window.qforge.credentials.clear();loadWorkspace();setLoggedIn(true);await loadTags();connectWs();try{await syncQuestions()}catch(e){log(`拉取题目失败: ${errMsg(e)}`)}renderAll();log(`登录成功: ${username}`)}catch(e){$("login-error").textContent=`登录失败: ${e.message}`}});
$("logout-button").addEventListener("click",()=>{state.token="";state.username="";state.wsConnected=false;state.selectedQuestionUuid="";state.entries.clear();state.ocrTasks.clear();if(state.ws){state.ws.close();state.ws=null}hideMenu();renderAll();setLoggedIn(false);log("已退出登录")});
$("screenshot-trigger-btn").addEventListener("click",async()=>{try{await window.qforge.screenshot.trigger()}catch(e){log(`截图启动失败: ${e.message}`)}});
$("create-task-btn").addEventListener("click",async()=>{try{hideMenu();await createTask()}catch(e){log(`新建失败: ${e.message}`)}});
$("create-batch-btn").addEventListener("click",async()=>{try{hideMenu();await createBatch()}catch(e){log(`批量创建失败: ${e.message}`)}});
$("start-ocr-btn").addEventListener("click",async()=>{try{await submitStemOcr()}catch(e){log(`OCR提交失败: ${e.message}`)}});
$("use-ocr-result-btn").addEventListener("click",()=>{try{fillLatest()}catch(e){log(`填充失败: ${e.message}`)}});
$("confirm-stem-btn").addEventListener("click",async()=>{try{await confirmStem()}catch(e){log(`题干确认失败: ${errMsg(e)}`)}});
$("add-answer-btn").addEventListener("click",async()=>{try{await addAnswer()}catch(e){log(`添加答案失败: ${e.message}`)}});
$("complete-btn").addEventListener("click",async()=>{try{await completeQ()}catch(e){log(`完成失败: ${e.message}`)}});
$("stem-textarea").addEventListener("input",()=>{const e=selectedEntry();if(!e)return;e.stemDraft=$("stem-textarea").value;e.updatedAt=Date.now();state.entries.set(e.questionUuid,e);saveWorkspace();renderLatex("stem-preview",e.stemDraft,"题干 LaTeX 预览区域")});
$("stem-secondary-tags-input").addEventListener("input",()=>{const e=selectedEntry();if(!e)return;e.secondaryTagsDraft=$("stem-secondary-tags-input").value;e.updatedAt=Date.now();state.entries.set(e.questionUuid,e);saveWorkspace()});
$("answer-textarea").addEventListener("input",()=>{const e=selectedEntry();if(!e)return;e.answerDraft=$("answer-textarea").value;e.updatedAt=Date.now();state.entries.set(e.questionUuid,e);saveWorkspace();renderLatex("answer-preview",e.answerDraft,"答案 LaTeX 预览区域")});
$("render-stem-btn").addEventListener("click",()=>renderLatex("stem-preview",$("stem-textarea").value,"题干 LaTeX 预览区域"));
$("render-answer-btn").addEventListener("click",()=>renderLatex("answer-preview",$("answer-textarea").value,"答案 LaTeX 预览区域"));
$("entry-delete-action").addEventListener("click",async()=>{const qid=$("entry-delete-action").dataset.questionUuid||state.contextMenuQuestionUuid;try{await delQ(qid)}catch(e){hideMenu();log(`删除失败: ${errMsg(e)}`)}});
$("completed-answer-tabs").addEventListener("click",ev=>{const target=ev.target;if(!(target instanceof HTMLElement))return;const btn=target.closest(".answer-tab");if(!btn)return;const idx=Number(btn.dataset.index);if(!Number.isFinite(idx))return;setCompletedAnswerIndex(idx)});
$("completed-prev-answer").addEventListener("click",()=>shiftCompletedAnswer(-1));$("completed-next-answer").addEventListener("click",()=>shiftCompletedAnswer(1));
document.addEventListener("click",ev=>{const m=$("entry-context-menu");if(!m.contains(ev.target))hideMenu()});window.addEventListener("blur",hideMenu);window.addEventListener("keydown",ev=>{if(ev.key==="Escape")hideMenu()});
window.qforge.screenshot.onCaptured(async p=>{try{await createByShot(p.imageBase64||"")}catch(e){log(`截图录题失败: ${e.message}`)}});window.qforge.screenshot.onError(p=>log(`截图服务异常: ${p.message||"未知错误"}`));}
async function boot(){state.config=await window.qforge.config.get();const key=state.config.screenshotShortcut||"CommandOrControl+Alt+A";$("screenshot-shortcut-label").textContent=key;$("status-shortcut").textContent=`截图快捷键: ${key}`;$("screenshot-trigger-btn").textContent=`截图录题 (${key})`;const remember=await window.qforge.credentials.load();if(remember.remember){$("login-username").value=remember.username||"";$("login-password").value=remember.password||"";$("remember-password").checked=true}bind();renderAll()}
boot().catch(e=>{$("login-error").textContent=`初始化失败: ${e.message}`;console.error(e)});
